from PyQt6 import QtWidgets, QtCore, QtGui
import sqlite3, sys

class Main(QtWidgets.QMainWindow):

    def __init__(self):
        super().__init__()
        self.setWindowTitle('STD-Manager')
        self.resize(1000,700)
        self.setMinimumSize(QtCore.QSize(1000, 700))
        self.setMaximumSize(QtCore.QSize(1000, 700))
        self.add_page = AddPage()
        self.del_page = DelPage()
        self.mod_page = ModPage()
        self.stack_container = QtWidgets.QStackedWidget()
        self.setCentralWidget(self.stack_container)
        self.stack_container.addWidget(self.add_page)
        self.stack_container.addWidget(self.del_page)
        self.stack_container.addWidget(self.mod_page)
        self.stack_container.setCurrentWidget(self.add_page)
        #labels
        self.vers_text = QtWidgets.QLabel('v0.2.0', self)
        self.vers_text.setGeometry(965, 680, 70, 20)
        self.vers_text.setObjectName('version_text')
        self.left_logo = QtWidgets.QLabel(self)
        self.left_logo.setGeometry(20, 20, 80, 60)
        self.left_logo.setObjectName('teachpg_left')
        #buttons
        self.add_btn = QtWidgets.QPushButton('ADD GRADE', self)
        self.add_btn.setGeometry(10, 200, 100, 50)
        self.add_btn.setObjectName('grades_btn_active')
        self.add_btn.clicked.connect(lambda: self.switch_frame(1))
        self.add_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.del_btn = QtWidgets.QPushButton('DEL GRADE', self)
        self.del_btn.setGeometry(10, 350, 100, 50)
        self.del_btn.setObjectName('grades_btn')
        self.del_btn.clicked.connect(lambda: self.switch_frame(2))
        self.del_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.mod_btn = QtWidgets.QPushButton('MOD GRADE', self)
        self.mod_btn.setGeometry(10, 500, 100, 50)
        self.mod_btn.setObjectName('grades_btn')
        self.mod_btn.clicked.connect(lambda: self.switch_frame(3))

    def switch_frame(self, page):
        if page == 2:
            self.stack_container.setCurrentWidget(self.del_page)
            self.add_btn.setObjectName('grades_btn')
            self.add_btn.setStyleSheet('styles.css')
            self.del_btn.setObjectName('grades_btn_active')
            self.del_btn.setStyleSheet('styles.css')
            self.mod_btn.setObjectName('grades_btn')
            self.mod_btn.setStyleSheet('styles.css')
        elif page == 1:
            self.stack_container.setCurrentWidget(self.add_page)
            self.add_btn.setObjectName('grades_btn_active')
            self.add_btn.setStyleSheet('styles.css')
            self.del_btn.setObjectName('grades_btn')
            self.del_btn.setStyleSheet('styles.css')
            self.mod_btn.setObjectName('grades_btn')
            self.mod_btn.setStyleSheet('styles.css')
        elif page == 3:
            self.stack_container.setCurrentWidget(self.mod_page)
            self.add_btn.setObjectName('grades_btn')
            self.add_btn.setStyleSheet('styles.css')
            self.del_btn.setObjectName('grades_btn')
            self.del_btn.setStyleSheet('styles.css')
            self.mod_btn.setObjectName('grades_btn_active')
            self.mod_btn.setStyleSheet('styles.css')
        else:
            print('error, page not found!')
        
class AddPage(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        #labels
        title = QtWidgets.QLabel('ADDING GRADES', self)
        title.setGeometry(400, 120, 300, 45)
        title.setObjectName('frame_title')
        f_name = QtWidgets.QLabel('FIRST NAME:', self)
        f_name.setGeometry(250, 220, 100, 20)
        f_name.setObjectName('frame_text')
        l_name = QtWidgets.QLabel('LAST NAME:', self)
        l_name.setGeometry(254, 280, 100, 20)
        l_name.setObjectName('frame_text')
        group = QtWidgets.QLabel('GROUP:', self)
        group.setGeometry(286, 340, 100, 20)
        group.setObjectName('frame_text')
        discipline = QtWidgets.QLabel('DISCIPLINE:', self)
        discipline.setGeometry(253, 400, 100, 20)
        discipline.setObjectName('frame_text')
        grade = QtWidgets.QLabel('GRADE:', self)
        grade.setGeometry(286, 460, 100, 20)
        grade.setObjectName('frame_text')
        #inputs
        self.fname_inp = QtWidgets.QLineEdit(self)
        self.fname_inp.setGeometry(350, 220, 200, 20)
        self.fname_inp.setObjectName('frame_input')
        self.lname_inp = QtWidgets.QLineEdit(self)
        self.lname_inp.setGeometry(350, 280, 200, 20)
        self.lname_inp.setObjectName('frame_input')
        self.group_inp = QtWidgets.QLineEdit(self)
        self.group_inp.setGeometry(350, 340, 200, 20)
        self.group_inp.setObjectName('frame_input')
        self.group_inp.setMaxLength(4)
        self.disci_inp = QtWidgets.QLineEdit(self)
        self.disci_inp.setGeometry(350, 400, 200, 20)
        self.disci_inp.setObjectName('frame_input')
        self.grade_inp = QtWidgets.QLineEdit(self)
        self.grade_inp.setMaxLength(2)
        self.grade_inp.setGeometry(350, 460, 200, 20)
        self.grade_inp.setObjectName('frame_input')
        #buttons
        self.send_add = QtWidgets.QPushButton('ADD', self)
        self.send_add.setGeometry(450, 520, 150, 40)
        self.send_add.setObjectName('grades_btn')


class DelPage(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        #labels
        title = QtWidgets.QLabel('DELETE GRADES', self)
        title.setGeometry(400, 120, 300, 45)
        title.setObjectName('frame_title')
        f_name = QtWidgets.QLabel('FIRST NAME:', self)
        f_name.setGeometry(250, 220, 100, 20)
        f_name.setObjectName('frame_text')
        l_name = QtWidgets.QLabel('LAST NAME:', self)
        l_name.setGeometry(254, 280, 100, 20)
        l_name.setObjectName('frame_text')
        group = QtWidgets.QLabel('GROUP:', self)
        group.setGeometry(286, 340, 100, 20)
        group.setObjectName('frame_text')
        discipline = QtWidgets.QLabel('DISCIPLINE:', self)
        discipline.setGeometry(253, 400, 100, 20)
        discipline.setObjectName('frame_text')
        grade = QtWidgets.QLabel('GRADE:', self)
        grade.setGeometry(286, 460, 100, 20)
        grade.setObjectName('frame_text')
        #inputs
        self.fname_inp = QtWidgets.QLineEdit(self)
        self.fname_inp.setGeometry(350, 220, 200, 20)
        self.fname_inp.setObjectName('frame_input')
        self.lname_inp = QtWidgets.QLineEdit(self)
        self.lname_inp.setGeometry(350, 280, 200, 20)
        self.lname_inp.setObjectName('frame_input')
        self.group_inp = QtWidgets.QLineEdit(self)
        self.group_inp.setGeometry(350, 340, 200, 20)
        self.group_inp.setObjectName('frame_input')
        self.group_inp.setMaxLength(4)
        self.disci_inp = QtWidgets.QLineEdit(self)
        self.disci_inp.setGeometry(350, 400, 200, 20)
        self.disci_inp.setObjectName('frame_input')
        self.grade_inp = QtWidgets.QLineEdit(self)
        self.grade_inp.setMaxLength(2)
        self.grade_inp.setGeometry(350, 460, 200, 20)
        self.grade_inp.setObjectName('frame_input')
        #buttons
        self.send_add = QtWidgets.QPushButton('DEL', self)
        self.send_add.setGeometry(450, 520, 150, 40)
        self.send_add.setObjectName('grades_btn')

class ModPage(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        #labels
        title = QtWidgets.QLabel('MODIFY GRADES', self)
        title.setGeometry(400, 120, 300, 45)
        title.setObjectName('frame_title')
        f_name = QtWidgets.QLabel('FIRST NAME:', self)
        f_name.setGeometry(250, 220, 100, 20)
        f_name.setObjectName('frame_text')
        l_name = QtWidgets.QLabel('LAST NAME:', self)
        l_name.setGeometry(254, 280, 100, 20)
        l_name.setObjectName('frame_text')
        group = QtWidgets.QLabel('GROUP:', self)
        group.setGeometry(286, 340, 100, 20)
        group.setObjectName('frame_text')
        discipline = QtWidgets.QLabel('DISCIPLINE:', self)
        discipline.setGeometry(253, 400, 100, 20)
        discipline.setObjectName('frame_text')
        grade = QtWidgets.QLabel('GRADE:', self)
        grade.setGeometry(286, 460, 100, 20)
        grade.setObjectName('frame_text')
        #inputs
        self.fname_inp = QtWidgets.QLineEdit(self)
        self.fname_inp.setGeometry(350, 220, 200, 20)
        self.fname_inp.setObjectName('frame_input')
        self.lname_inp = QtWidgets.QLineEdit(self)
        self.lname_inp.setGeometry(350, 280, 200, 20)
        self.lname_inp.setObjectName('frame_input')
        self.group_inp = QtWidgets.QLineEdit(self)
        self.group_inp.setGeometry(350, 340, 200, 20)
        self.group_inp.setObjectName('frame_input')
        self.group_inp.setMaxLength(4)
        self.disci_inp = QtWidgets.QLineEdit(self)
        self.disci_inp.setGeometry(350, 400, 200, 20)
        self.disci_inp.setObjectName('frame_input')
        self.grade_inp = QtWidgets.QLineEdit(self)
        self.grade_inp.setMaxLength(2)
        self.grade_inp.setGeometry(350, 460, 200, 20)
        self.grade_inp.setObjectName('frame_input')
        
        #buttons
        self.send_add = QtWidgets.QPushButton('MOD', self)
        self.send_add.setGeometry(450, 520, 150, 40)
        self.send_add.setObjectName('grades_btn')

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    with open('styles/style.css', 'r') as f:
        stylesheet = f.read()
    app.setStyleSheet(stylesheet)
    window = Main()
    window.show()
    sys.exit(app.exec())
